### ISSUE TITLE
Getting TypeError: element.setAttribute is not a function in console

### ISSUE THREAD

**Issue by lbecraft** [michaelbromley/angularUtils#163]
The page loads and pagination works but getting this error in console. 

TypeError: element.setAttribute is not a function
    at forEach.attr (http://localhost:9000/vendor/angular/angular.js:2887:15)
    at Object.JQLite.(anonymous function) [as attr] (http://localhost:9000/vendor/angular/angular.js:2986:9)
    at Object.$get.Attributes.$set (http://localhost:9000/vendor/angular/angular.js:6829:28)
    at interpolateFnWatchAction (http://localhost:9000/vendor/angular/angular.js:8157:28)
    at interpolateFnWatcher (http://localhost:9000/vendor/angular/angular.js:10216:26)
    at Object.watchGroupAction [as fn] (http://localhost:9000/vendor/angular/angular.js:13980:13)
    at Scope.$get.Scope.$digest (http://localhost:9000/vendor/angular/angular.js:14308:29)
    at Scope.$get.Scope.$apply (http://localhost:9000/vendor/angular/angular.js:14571:24)
    at bootstrapApply (http://localhost:9000/vendor/angular/angular.js:1455:15)
    at Object.invoke (http://localhost:9000/vendor/angular/angular.js:4203:17)

TypeError: element.setAttribute is not a function
    at forEach.attr (http://localhost:9000/vendor/angular/angular.js:2887:15)
    at Object.JQLite.(anonymous function) [as attr] (http://localhost:9000/vendor/angular/angular.js:2986:9)
    at Object.$get.Attributes.$set (http://localhost:9000/vendor/angular/angular.js:6829:28)
    at interpolateFnWatchAction (http://localhost:9000/vendor/angular/angular.js:8157:28)
    at interpolateFnWatcher (http://localhost:9000/vendor/angular/angular.js:10216:26)
    at Object.watchGroupAction [as fn] (http://localhost:9000/vendor/angular/angular.js:13980:13)
    at Scope.$get.Scope.$digest (http://localhost:9000/vendor/angular/angular.js:14308:29)
    at Scope.$get.Scope.$apply (http://localhost:9000/vendor/angular/angular.js:14571:24)
    at done (http://localhost:9000/vendor/angular/angular.js:9698:47)
    at completeRequest (http://localhost:9000/vendor/angular/angular.js:9888:7)

**Comment by michaelbromley** [comment]
Could you post your view code where you use the directives? Also what browser is this happening in?

**Comment by lbecraft** [comment]
Michael,
Thank you for looking into this.
This is happening in firefox, chrome and safari.



Controller here:
```javascript
(function(module) {
    
    module.controller('AppmodelsController', function (Appmodel) {
        var model = this;
        model.loading = false;
        model.appmodels = [];

        model.totalCount = 0;
        model.itemsPerPage = 10;
        model.pagination = { current: 1 };
        model.pageChanged = pageChanged;

        init();

        function init() {
            getAppmodels();
        }

        function getAppmodels(pageNumber) {
            model.loading = true;
            Appmodel.query({page: pageNumber}, function success(data, headers){
                model.appmodels = data;
                model.totalCount = headers('x-totalcount');
                model.itemsPerPage = headers('x-itemsperpage');
            });
        }

        function pageChanged(newPage) {
            getAppmodels(newPage);
        }
    });
    
}(angular.module("asPlatformClient.appmodels")));
```

Template here:
```html
<table class="table">
    <tr>
        <th>Name</th>
        <th>Description</th>
    </tr>
    <tr dir-paginate="appmodel in model.appmodels | itemsPerPage: 10" total-items="{{model.totalCount}}" current-page="pagination.current">
        <td>{{appmodel.name}}</td>
        <td>{{appmodel.description}}</td>
    </tr>
</table>

<dir-pagination-controls on-page-change="model.pageChanged(newPageNumber)"></dir-pagination-controls>```

**Comment by michaelbromley** [comment]
Can't see anything unusual about your code. 

1. What version of Angular are you using?
2. Does this error only happen when you use the pagination directives?
3. Are you able to reproduce it in a plunker?
4. Have you tried setting a breakpoint at line 2887 of the `angular.js` script to see what the value of `element` is which is causing the error? This might lead you to the source of the error.

**Comment by lbecraft** [comment]
I set the break point at ine 2887 of the angular.js and it was failing on element "total-items"
On the first pass the total-items = 0
2nd pass total-items = 23

The error went away when I changed 
```javascript
total-items="{{model.totalCount}}" 
```
To
```javascript
total-items="model.totalCount" 
```
1. angular 1.3.15
2. Error only happens with pagination directives.

**Comment by michaelbromley** [comment]
Ah right, I missed that when looking over your view code.

So you found the error - the `total-items` attribute should not contain {{}}.
