### ISSUE TITLE
Unexpected end of expression: setCurrent(pagination

### ISSUE THREAD

**Issue by marcfielding1** [michaelbromley/angularUtils#187]
Hi,

I seem to be having an issue with pagination using the example from here, abbreviated code is as follows:
```HTML
<table>
<tr dir-paginate="transaction in transactions | itemsPerPage: 50" total-items="numberOfRecords" current-page="pagination.current" ng-click="viewTransaction(transaction)">
 
</tr>
</table>

<dir-pagination-controls on-page-change="pageChanged(newPageNumber)"></dir-pagination-controls>
```

The data for the table is pulled in 50 records at a time from an API it actually shows the right number of pages and the control but obviously none of the buttons work.

Exact error is:
```HTML
Error: [$parse:ueoe] http://errors.angularjs.org/1.3.16/$parse/ueoe?p0=setCurrent(pagination
    at Error (native)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.3.16/angular.min.js:6:417
    at lb.consume (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.16/angular.min.js:192:410)
    at lb.functionCall (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.16/angular.min.js:199:301)
    at lb.primary (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.16/angular.min.js:191:249)
    at lb.unary (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.16/angular.min.js:198:234)
    at lb.multiplicative (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.16/angular.min.js:197:466)
    at lb.additive (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.16/angular.min.js:197:324)
    at lb.relational (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.16/angular.min.js:197:190)
    at lb.equality (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.16/angular.min.js:197:46) <a href="" ng-click="setCurrent(pagination.current - 1)">
```
I've tried to keep this short and sweet if you need more detail let me know!

**Comment by michaelbromley** [comment]
Hi,

Just from looking at the code you posted, I can't see anything obviously wrong. If I were you I'd first try using the unminified version of angular.js and set a breakpoint at the line where the error occurs, and then see what the "unexpected end of expression" error is referring to. That might give you some pointer towards what is really going wrong.

**Comment by marcfielding1** [comment]
Hi sorry for the delayed reply.

It's really rather odd if I clear browser data in chrome the error goes away, then comes back after reloading the page a couple of times?

**Comment by michaelbromley** [comment]
Yeah that's strange. Could it be that your server response is sometimes sending bad data (e.g. an invalid value for the "total") and then it is getting cached?

**Comment by mphfish** [comment]
@marcfielding1 I ran into the exact same issue as you.  As a work around, I added the following methods to dirPagination.js, and modified the templates accordingly:

```javascript
            scope.pageBack = function () {
              scope.setCurrent(scope.pagination.current - 1);
            };

            scope.pageForward = function () {
                scope.setCurrent(scope.pagination.current + 1);
            };
```

Not quite sure what the root cause is, but there's something happening in the ng-click directive that Angular is falling down on.

**Comment by pywebdesign** [comment]
got the same problem!

````
Error: [$parse:ueoe] Unexpected end of expression: setCurrent(pagination
http://errors.angularjs.org/1.3.15/$parse/ueoe?p0=setCurrent(pagination
    at REGEX_STRING_REGEXP (http://localhost:3000/assets/angular/angular-5dbfd89d472d4d7e5fef444bd7777eaf.js?body=1:64:12)
    at Parser.consume (http://localhost:3000/assets/angular/angular-5dbfd89d472d4d7e5fef444bd7777eaf.js?body=1:12108:13)
    at Parser.functionCall (http://localhost:3000/assets/angular/angular-5dbfd89d472d4d7e5fef444bd7777eaf.js?body=1:12383:10)
    at Parser.primary (http://localhost:3000/assets/angular/angular-5dbfd89d472d4d7e5fef444bd7777eaf.js?body=1:12055:24)
    at Parser.unary (http://localhost:3000/assets/angular/angular-5dbfd89d472d4d7e5fef444bd7777eaf.js?body=1:12331:19)
    at Parser.multiplicative (http://localhost:3000/assets/angular/angular-5dbfd89d472d4d7e5fef444bd7777eaf.js?body=1:12314:21)
    at Parser.additive (http://localhost:3000/assets/angular/angular-5dbfd89d472d4d7e5fef444bd7777eaf.js?body=1:12305:21)
    at Parser.relational (http://localhost:3000/assets/angular/angular-5dbfd89d472d4d7e5fef444bd7777eaf.js?body=1:12296:21)
    at Parser.equality (http://localhost:3000/assets/angular/angular-5dbfd89d472d4d7e5fef444bd7777eaf.js?body=1:12287:21)
    at Parser.logicalAND (http://localhost:3000/assets/angular/angular-5dbfd89d472d4d7e5fef444bd7777eaf.js?body=1:12278:21) <a href="" ng-click="setCurrent(pagination.current+1)">
````

**Comment by marcfielding1** [comment]
I think it might be batarang, when I disable it, no errors

**Comment by michaelbromley** [comment]
Thanks for the reports and possible reason @marcfielding1. @pywebdesign and @mphfish do you also have Batarang enabled? Does the error go away if you disable?

**Comment by mphfish** [comment]
I can confirm, disabling Batarang fixes the issue.  Bad Batarang!

**Comment by pywebdesign** [comment]
yeah it seams so!
