### ISSUE TITLE
Not working in asp.net mvc

### ISSUE THREAD

**Issue by vijaysaklani** [michaelbromley/angularUtils#388]
Hi i am trying to implement this in asp.net mvc. But not working. I have try all solutions. Here is my code:
```
@{
    ViewBag.Title = "AngualarJs Tutorial";
}
<style>
    .odd {
        background-color: antiquewhite;
        color: #008b8b;
    }

    td th {
        height: 30px;
        min-width: 100px;
    }

    thead {
        background-color: darkgray;
        color: white;
        height: 30px;
    }  
</style>
<h2>AngualarJs Tutorial : CRUD opration</h2>
<div ng-app="mvcapp" ng-controller="DemoController">
    <form method="post" name="myform">
        <table class="table">
            <tr>
                <td>Name :</td>
                <td>
                    <input type="text" name="name" maxlength="4" ng-model="empModel.Name" placeholder="Name" class='form-control' required />
                                       
                </td>
            </tr>
            <tr>
                <td>Phone :</td>
                <td>
                    <input type="number" name="phone" ng-model="empModel.Phone" maxlength="10" placeholder="Phone" class='form-control' required />  
                                          
                </td>
            </tr>
            <tr>
                <td>Salary :</td>
                <td>
                    <input type="number" name="Salary" ng-model="empModel.Salary" placeholder="Salary" class='form-control' ng-required="" />
                 
                </td>
            </tr>
            <tr>
                <td>Department :</td>
                <td>
                    <input type="text" name="department" ng-model="empModel.Department" placeholder="Department" class='form-control' required />
                  
                </td>
            </tr>
            <tr>
                <td>Email :</td>
                <td>
                    <input type="email"  ng-model="empModel.EmailId" class='form-control' placeholder="Email" required />                    
                </td>
            </tr>         
            <tr>
                <td></td>
                <td>
                    <input type="submit" value="submit" id="btnsave" ng-disabled="isDisabledsave" ng-click="myform.$valid && saveCustomer()" />
                    <input type="button" value="Update" id="btnupdate" ng-disabled="isDisabledupdate" ng-click="myform.$valid && updateCustomer()" />
                </td>
            </tr>
        </table>
    </form>
    <dir-pagination-controls max-size="5"
                             direction-links="true"
                             boundary-links="true">
    </dir-pagination-controls>
    <table class="table table-striped">
        <tr>
            <th>S.No</th>

            <th>
                Name
            </th>
            <th>
                Phone
            </th>
            <th>
                Department
            </th>
            <th>
                Salary
            </th>
            <th>
                Email
            </th>
            <th></th>
            <th></th>
        </tr>

        <tr dir-paginate="empModel in employees| itemsPerPage: 10">
            <td>{{empModel.Id}}</td>
            <td>{{empModel.Name }}</td>
            <td>{{empModel.Phone }}</td>
            <td>{{empModel.Department}}</td>
            <td>{{empModel.Salary }}</td>
            <td>{{empModel.EmailId ||'Email not available'}}</td>
            <td><img ng-src={{empModel.ImagePath||'images/image.jpg'}} alt="" title="{{emp.Name}}" width="150" height="150" /> </td>
            <td>
                <a href="" ng-click="getCustomer(empModel)" title="Delete Record">Edit</a>  |
                <a href="" ng-click="deleteemp(empModel)" title="Delete Record">
                    Delete
                </a>
            </td>
        </tr>
       
    </table>
    <ul>
        <li ng-repeat="empModel in employees">{{empModel.Name}}</li>
    </ul>

    <dir-pagination-controls boundary-links="true" template-url="../dirPagination.tpl.html"></dir-pagination-controls>

    <ul class="pagination" ng-if="1 < pages.length || !autoHide">
        <li ng-if="boundaryLinks" ng-class="{ disabled : pagination.current == 1 }">
            <a href="" ng-click="setCurrent(1)">&laquo;</a>
        </li>
        <li ng-if="directionLinks" ng-class="{ disabled : pagination.current == 1 }">
            <a href="" ng-click="setCurrent(pagination.current - 1)">&lsaquo;</a>
        </li>
        <li ng-repeat="pageNumber in pages track by tracker(pageNumber, $index)" ng-class="{ active : pagination.current == pageNumber, disabled : pageNumber == '...' }">
            <a href="" ng-click="setCurrent(pageNumber)">{{ pageNumber }}</a>
        </li>
        <li ng-if="directionLinks" ng-class="{ disabled : pagination.current == pagination.last }">
            <a href="" ng-click="setCurrent(pagination.current + 1)">&rsaquo;</a>
        </li>
        <li ng-if="boundaryLinks" ng-class="{ disabled : pagination.current == pagination.last }">
            <a href="" ng-click="setCurrent(pagination.last)">&raquo;</a>
        </li>
    </ul>
</div>

<style>
    input[type=button][disabled=disabled] {
        opacity: 0.65;
        cursor: not-allowed;
    }
    table tr th {
        padding: 10px 30px;
    }
    table tr td {
        padding: 10px 30px;
    }
</style>


<script src="https://code.angularjs.org/1.3.0/angular.js"></script>
<script src="http://code.jquery.com/jquery-2.0.3.min.js"></script>
@*<script src="http://code.angularjs.org/1.4.8/angular-resource.js"></script>*@
<script src="http://angular-ui.github.io/bootstrap/ui-bootstrap-tpls-0.12.1.min.js"></script> 
@*<script src="~/js/angular-table.js"></script>*@
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
@*<script src="~/js/ui-bootstrap-tpls-0.11.0.js"></script>*@

@*<script src="~/Scripts/angular-messages.min.js"></script>*@

    
        <script src="~/js/dirPagination.js"></script>
<script>
    var angular = angular.module('mvcapp', ['angularUtils.directives.dirPagination']);

    angular.controller('DemoController', function ($scope, $http) {

        
        $scope.isDisabledupdate = true;
        //Get All Employee
        $scope.employees = [];
        $http.get('/Demo/GetEmployee').success(function (data) {
            $scope.employees = [];
        
            $scope.employees = data;
            $scope.currentPage = 1;
            $scope.pageSize = 10;
        });
       
        //Insert Employee
        $scope.saveCustomer = function () {
            debugger
            $http({
                method: 'POST',
                url: '/Demo/InsertEmployee',
                data: $scope.empModel
            }).success(function () {
                GetAllData();
                $scope.empModel = null;
                alert("Employee Added Successfully!!!");
            }).error(function () {
                alert(data.errors);
            });
            GetAllData();
        };

        //Delete Employee
        $scope.deleteemp = function (empModel) {
            debugger
            varIsConf = confirm('Want to delete ' + empModel.Name + '. Are you sure?');
            if (varIsConf) {
                $http.delete('/Demo/DeleteEmployee/' + empModel.Id).success(function () {
                    $scope.errors = [];
                    GetAllData();
                    alert(empModel.Name + " Deleted Successfully!!!");
                }).error(function () {
                    alert(data.errors);
                });
            }
        };

        //Get Employee by id to edit
        $scope.getCustomer = function (empModel) {
            $http.get('/Demo/getByid/' + empModel.Id)
            .success(function (data, status, headers, config) {
                //debugger;
                $scope.empModel = data;
                GetAllData();
                $scope.isDisabledsave = true;
                $scope.isDisabledupdate = false;
            })
            .error(function () {
                alert(data.errors);
            });
        };

        //Update Employee
        $scope.updateCustomer = function () {
            debugger
            $http({
                method: 'POST',
                url: '/Demo/UpdateEmployee',
                data: $scope.empModel
            }).success(function () {
                GetAllData();
                $scope.isDisabledsave = false;
                $scope.isDisabledupdate = true;
                $scope.empModel = null;
                alert("Employee Updated Successfully!!!");
            }).error(function () {
                alert(data.errors);
            });
        };

    });
</script>
```

`
here is the error in console:
```
> angular.js:11358 TypeError: angular.forEach is not a function
    at addNoCompileAttributes (http://localhost:3816/js/dirPagination.js:165:21)
    at Object.dirPaginationCompileFn [as compile] (http://localhost:3816/js/dirPagination.js:59:13)
    at applyDirectivesToNode (https://code.angularjs.org/1.3.0/angular.js:7362:32)
    at compileNodes (https://code.angularjs.org/1.3.0/angular.js:6913:15)
    at compileNodes (https://code.angularjs.org/1.3.0/angular.js:6925:15)
    at compileNodes (https://code.angularjs.org/1.3.0/angular.js:6925:15)
    at compileNodes (https://code.angularjs.org/1.3.0/angular.js:6925:15)
    at compile (https://code.angularjs.org/1.3.0/angular.js:6834:15)
    at https://code.angularjs.org/1.3.0/angular.js:1489:11
    at Scope.$eval (https://code.angularjs.org/1.3.0/angular.js:14123:28) <tr dir-paginate="empModel in employees| itemsPerPage: 10">(anonymous function) @ angular.js:11358(anonymous function) @ angular.js:8445applyDirectivesToNode @ angular.js:7369compileNodes @ angular.js:6913compileNodes @ angular.js:6925compileNodes @ angular.js:6925compileNodes @ angular.js:6925compile @ angular.js:6834(anonymous function) @ angular.js:1489$eval @ angular.js:14123$apply @ angular.js:14221bootstrapApply @ angular.js:1487invoke @ angular.js:4152doBootstrap @ angular.js:1485bootstrap @ angular.js:1505angularInit @ angular.js:1399(anonymous function) @ angular.js:25579trigger @ angular.js:2742eventHandler @ angular.js:3013
dirPagination.js:271 Pagination directive: the pagination controls cannot be used without the corresponding pagination directive, which was not found at link time.
```

**Comment by michaelbromley** [comment]
Hi,

I don't really get what you are trying to do here. You seem to be embedding a custom template right in your view code. That's not how it's supposed to work - if you want a custom template, you should put it in a separate html file and reference that file with the `template-url` attribute.

Since this is a bit of a non-specific issue, and seems like more of just a "help with getting started" request, I suggest you 1) carefully study the docs to figure out how to implement the directives and 2) try asking on StackOverflow. I'm afraid I don't have the time to dedicate to it myself.

Good luck!
