### ISSUE TITLE
dirPaginate: Error on clicking pagination links.

### ISSUE THREAD

**Issue by EnnKkay** [michaelbromley/angularUtils#54]
Hi, I am getting the following error on clicking on any of the pagination links. Could you please advise as to what would be causing this? Thanks.

[15:58:50.284] "Error: instances[instanceId].currentPageParser.assign is not a function
@http://localhost:8080/psi4web/js/dirPagination.js:299
.link/scope.setCurrent@http://localhost:8080/psi4web/js/dirPagination.js:213
Za.prototype.functionCall/<@https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.2/angular.min.js:190
qc[c]</<.compile/</</f@https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.2/angular.min.js:218
k.prototype.$eval@https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.2/angular.min.js:120
k.prototype.$apply@https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.2/angular.min.js:121
qc[c]</<.compile/</<@https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.2/angular.min.js:218
n.event.dispatch@http://code.jquery.com/jquery-1.11.0.min.js:3
n.event.add/r.handle@http://code.jquery.com/jquery-1.11.0.min.js:3"

Here are the relevant code pieces

```
<tbody>
     <tr dir-paginate="entity in entities | itemsPerPage: 20" current-page="1">
          <td ng-repeat="(key, value) in entity.nameValues">{{value}}</td>
     </tr>  
</tbody>
```

```
<div>
      <dir-pagination-controls boundary-links="true" template-url="./js/dirPagination.tpl.html">
      </dir-pagination-controls>
</div>
```

**Comment by ashokgavini** [comment]
i need to show loadbar when clicking on pagination number......

my code : <div class="search_list" dir-paginate="icd in icdslist| filter:q | itemsPerPage: pageSize"  current-page="currentPage">
                                            <span class="left_code">{{ icd.ICD }}</span> <span class="right_disc">{{ icd.Description1 }} & {{ icd.Description2 }}</span>
                                        </div>
                                    <div class="row">
                                        <div class="text-center">
                                            <dir-pagination-controls boundary-links="true" on-page-change="pageChangeHandler(newPageNumber)" template-url="dirPagination.tpl.html"></dir-pagination-controls>
                                        </div>
                                    </div>   



controller:
    $scope.pageChangeHandler = function (num) {
        console.log('icds page changed to ' + num);
        $scope.currentPage = num;
        $scope.loadItems();
       
    };
    $scope.loadItems = function () {
        $scope.IsLoad = true;
        var response = $scope.icdslist.allPaged($scope.pageSize, $scope.currentPage - 1); // backend starts counting from 0
        response.$promise.then(function () {
            $scope.icdslist = response.data;
            $scope.total = response.details.total;
            $scope.IsLoad = false;
            });
        };


error:angular.min.js:495 TypeError: $scope.icdslist.allPaged is not a function
    at m.$scope.loadItems (http://localhost:43367/app/Controllers/icdsearchController.js:42:40)
    at m.$scope.pageChangeHandler (http://localhost:43367/app/Controllers/icdsearchController.js:37:16)
    at fn (eval at compile (http://localhost:43367/JS/angular.min.js:979:495), <anonymous>:4:336)
    at m.d.(anonymous function) [as onPageChange] (http://localhost:43367/JS/angular.min.js:340:323)
    at goToPage (http://localhost:43367/JS/dirPagination.js:279:35)
    at http://localhost:43367/JS/dirPagination.js:255:25
    at m.$digest (http://localhost:43367/JS/angular.min.js:603:243)
    at m.$apply (http://localhost:43367/JS/angular.min.js:616:411)
    at HTMLAnchorElement.<anonymous> (http://localhost:43367/JS/angular.min.js:1126:505)
    at HTMLAnchorElement.dispatch (http://localhost:43367/JS/jquery.js:3:12344)(anonymous function) @ angular.min.js:495(anonymous function) @ angular.min.js:370$digest @ angular.min.js:607$apply @ angular.min.js:616(anonymous function) @ angular.min.js:1126dispatch @ jquery.js:3r.handle @ jquery.js:3

**Comment by Sardar-Ali-Murad** [comment]
https://embed.plnkr.co/z3Gl6uBnC34cQiEyeInm
